- .gitignore
- cmd/rep/main_suite_test.go
- generator/internal/internal_suite_test.go
Interrupting a process doesn't work on windows, but kill seems to be
doing the job. Since this is a cleanup step after all tests have run,
kill and interrupt should be equivalent.
> Use kill instead of interrupt to stop etcd

- client_test.go
Go 1.5 will return a different error message for http timeout.
Ref: https://github.com/golang/go/issues/9405
> Update client test to mach go 1.5 http errors

- cmd/rep/main_test.go
- Uses 127.0.0.1 instead of 0.0.0.0
- Uses KillWithFire instead of Interrupt since signals don't work on win
- Skips a test that explicitly relies on `Interrupt` which isn't supported on windows
[#104201496]
> fixes the tests on windows

- harmonizer/bulker_test.go
- maintain/maintain_test.go
There seems to be sync issues with the fake clock in some tests. I had to debug them previously to make sure they are not windows related. I saw that @mhoran also experienced this issue so I am making a PR out of this fix.
This flaky errors seams to also appear on on linux + go1.5.1.
Errors:
* 1
```
------------------------------
• Failure [1.016 seconds]
Maintain Presence
C:/Users/stefans/gowp/src/github.com/cloudfoundry-incubator/rep/maintain/maintain_test.go:265
when pinging the executor succeeds
C:/Users/stefans/gowp/src/github.com/cloudfoundry-incubator/rep/maintain/maintain_test.go:264
when the heartbeater is ready
C:/Users/stefans/gowp/src/github.com/cloudfoundry-incubator/rep/maintain/maintain_test.go:263
when the executor ping fails …
```
> Fix test race in maintain and harmonizer pkg

- cmd/rep/config/config.go
- cmd/rep/config/config_test.go
- cmd/rep/main.go
- cmd/rep/main_suite_test.go
- generator/internal/internal_suite_test.go
This PR goes along with [this one](https://github.com/cloudfoundry/consuladapter/pull/7) that adds support for a TLS consul client. This is in support of the work to make consul<->rep communication more secure on Windows.
Let me know if there is anything that I should add!
> Use TLS consul client if consul cluster specifies https

- conversion_helpers.go
- conversion_helpers_test.go
- generator/internal/evacuation_lrp_processor_test.go
- generator/internal/ordinary_lrp_processor_test.go
This is a comprehensive set of PRs that must be merged at the same:
- [bbs](https://github.com/cloudfoundry/bbs/pull/39)
- [diego-ssh](https://github.com/cloudfoundry/diego-ssh/pull/45)
- [executor](https://github.com/cloudfoundry/executor/pull/46)
- [rep](https://github.com/cloudfoundry/rep/pull/28)
- [route-emitter](https://github.com/cloudfoundry/route-emitter/pull/14)
This change enables `rep` to advertise connection preference: Diego cell IP vs Instance (Container) IP.
Silk, the default container network plugin, prefers connecting to the Diego cell's IP address, and that's the default behavior.
Third party network plugins will now have the option to advertise the instance (container) IP address when they are placed on a separate overlay network.
To enable this behavior, set the `rep` …
> Enable `cf ssh` for Windows+Linux with 3rd Party Network Plugins

- auctioncellrep/auction_cell_rep.go
- auctioncellrep/auction_cell_rep_test.go
- cmd/rep/config/config.go
- cmd/rep/config/config_test.go
- cmd/rep/main.go
- resources.go
- resources_test.go
This PR is part of multiple PRs across [rep](https://github.com/cloudfoundry/rep), [auctioneer](https://github.com/cloudfoundry/auctioneer) and [auction](https://github.com/cloudfoundry/auction) to add an optional weighted bin pack first fit component to the scheduling algorithm of Cloud Foundry Diego for scheduling LRPs.
PRs/issues involved:
* [rep#30](https://github.com/cloudfoundry/rep/pull/30)
* [auctioneer#8](https://github.com/cloudfoundry/auctioneer/pull/8)
* [auction#8](https://github.com/cloudfoundry/auction/pull/8)
* [diego-release#448](https://github.com/cloudfoundry/diego-release/pull/448)
These PRs combined introduce a new setting for auctioneer:
```
diego.auctioneer.bin_pack_first_fit_weight
description: "Factor to bias against BOSH instance index number of a cell. Instead …
```
> make cell_index config item part of CellState object

- cmd/rep/config/config_test.go
Thank you for submitting a pull request to the rep repository!
We appreciate the contribution. To help us understand the context for your pull request, please fill out this template to the best of your ability.
1. Check the [Contributing document](https://github.com/cloudfoundry/diego-release/blob/develop/CONTRIBUTING.md) on how to sign the CLA and run tests.
1. Submit your PR to this repo.
1. [**Submit an accompanying PR Review Request**](https://github.com/cloudfoundry/diego-release/issues/new?assignees=&labels=&template=pr-review-request.md&title=%5BREP+PR+REVIEW%5D%3A) referencing this PR so the Diego Team knows to review your pull request. 
* **Note: this PR will not be reviewed unless you submit the [PR Review Request](https://github.com/cloudfoundry/diego-release/issues/new?assignee …
> Add new Executor property to config test

- conversion_helpers.go
- conversion_helpers_test.go
Internal routes will be used in SAN of C2C TLS certificate. We need to
pass them from desired LRP to the executor.
[#180173340](https://www.pivotaltracker.com/story/show/180173340)
> Add internal routes to executor RunInfo

- generator/internal/evacuation_lrp_processor.go
- generator/internal/evacuation_lrp_processor_test.go
- generator/internal/ordinary_lrp_processor.go
- generator/internal/ordinary_lrp_processor_test.go
Update BBS Client within the Rep to use the new `StartActualLRP` and `EvacuateRunningActualLRP`
Support TLS on container to container (c2c) communication by converging internal routes.
If the synchronous communication between BBS and Rep does not work, then the actual lrp will not be updated with the correct internal routes.
Ensure containers can eventually communicate over TLS using application internal route even if synchronous communication fails
https://github.com/cloudfoundry/diego-release/issues/588
https://github.com/cloudfoundry/diego-release/issues/587
https://www.pivotaltracker.com/story/show/180426889
https://github.com/cloudfoundry/bbs/pull/46
https://github.com/cloudfoundry/diego-release/pull/617
@selzoc 
Thank you!
> Use new bbsclient with internal routes

- client.go
- client_test.go
- cmd/rep/main_test.go
- generator/internal/evacuation_lrp_processor.go
- generator/internal/evacuation_lrp_processor_test.go
- generator/internal/ordinary_lrp_processor.go
- generator/internal/ordinary_lrp_processor_test.go
- handlers/handlers.go
- routes.go
Thank you for submitting a pull request to the rep repository!
We appreciate the contribution. To help us understand the context for your pull request, please fill out this template to the best of your ability.
1. Check the [Contributing document](https://github.com/cloudfoundry/diego-release/blob/develop/CONTRIBUTING.md) on how to sign the CLA and run tests.
1. Submit your PR to this repo.
1. ~~[**Submit an accompanying PR Review Request**](https://github.com/cloudfoundry/diego-release/issues/new?assignees=&labels=&template=pr-review-request.md&title=%5BREP+PR+REVIEW%5D%3A) referencing this PR so the Diego Team knows to review your pull request.~~ 
* ~~**Note: this PR will not be reviewed unless you submit the [PR Review Request](https://github.com/cloudfoundry/diego-release/issues/new?as …
> Converge metric tags

- client.go
- client_test.go
- cmd/rep/main_test.go
- generator/internal/evacuation_lrp_processor.go
- generator/internal/evacuation_lrp_processor_test.go
- generator/internal/ordinary_lrp_processor.go
- generator/internal/ordinary_lrp_processor_test.go
- handlers/handlers.go
- handlers/update_lrp_handler.go
- handlers/update_lrp_handler_test.go
- resources.go
- routes.go
Thank you for submitting a pull request to the rep repository!
We appreciate the contribution. To help us understand the context for your pull request, please fill out this template to the best of your ability.
1. Check the [Contributing document](https://github.com/cloudfoundry/diego-release/blob/develop/CONTRIBUTING.md) on how to sign the CLA and run tests.
1. Submit your PR to this repo.
1. ~~[**Submit an accompanying PR Review Request**](https://github.com/cloudfoundry/diego-release/issues/new?assignees=&labels=&template=pr-review-request.md&title=%5BREP+PR+REVIEW%5D%3A) referencing this PR so the Diego Team knows to review your pull request.~~ 
* ~~**Note: this PR will not be reviewed unless you submit the [PR Review Request](https://github.com/cloudfoundry/diego-release/issues/new?as …
> Update metric tags

- cmd/rep/main_test.go
Most of the code in there includes calls to Eventually and Wait, so we don't need the goroutine/done channel logic.
The only possible issue is fakeGarden.Close, which includes code that acquires/releases a mutex. If we find that tests are hanging on that line, we'll need to wrap that single line in a goroutine managed by a done channel
> Move AfterEach logic out of goroutine

- auctioncellrep/auction_cell_rep.go
- generator/internal/evacuation_lrp_processor_test.go
- generator/internal/ordinary_lrp_processor_test.go
- handlers/cancel_task_handler.go
- handlers/cancel_task_handler_test.go
- handlers/container_metrics_handler.go
- handlers/container_metrics_handler_test.go
- handlers/evacuation_handler.go
- handlers/handlers_suite_test.go
- handlers/perform_handler.go
- handlers/perform_handler_test.go
- handlers/reset_handler.go
- handlers/reset_handler_test.go
- handlers/state_handler.go
- handlers/state_handler_test.go
- handlers/stop_lrp_handler.go
- handlers/stop_lrp_handler_test.go
- handlers/update_lrp_handler.go
- handlers/update_lrp_handler_test.go
Update Rep logging calls to use new `WithTraceInfo()` method, which appends an `trace-id` based on the `VCAP_REQUEST_ID`. This will allow users to trace a request from Gorouter through Diego components. See https://github.com/cloudfoundry/lager/commit/1e35ce1b4e07747ee2f0fa29052ef0f8c56ed3bd
Allows operators to troubleshoot a workflow through multiple components of CF.
Add zipkin trace-id to Diego (using lager `WithTraceInfo()` method).
> With distributed tracing

- generator/internal/evacuation_lrp_processor_test.go
- generator/internal/ordinary_lrp_processor_test.go
> _Address incorrectly written test within rep's generator/internal lrp process evacuation tests._
> _Tests will not pass._
> Fix incorrectly written log line test

- handlers/container_metrics_handler_test.go
Expect new cache fields which has been introduced with https://github.com/cloudfoundry/executor/pull/83/files#diff-ce7c6acd1213d11c38682fac36c436010409569ee2001df1a5f78fce95c57770R10-R11.
Stakeholders can't observe the network traffic usage for a particular app. 
`cf tail -c metrics <app-guid> -f`  will not show `rx_bytes` and `tx_bytes`.
Container network traffic is now being sent to the logging stack.
* https://cloudfoundry.slack.com/archives/C01ABMVNE9E/p1683732484532129
* https://github.com/cloudfoundry/cf-networking-release/issues/64
* https://github.com/JVecsei1
must be merged first: 
* https://github.com/cloudfoundry/diego-logging-client/pull/82
* https://github.com/cloudfoundry/executor/pull/83
> enhance test to expect new network traffic usage fields

- cmd/rep/main.go
- generator/generator.go
- generator/generator_test.go
- generator/internal/evacuation_lrp_processor.go
- generator/internal/evacuation_lrp_processor_test.go
- generator/internal/lrp_processor.go
- generator/internal/ordinary_lrp_processor.go
- generator/internal/ordinary_lrp_processor_test.go
Rep will pass availability zone it is configured with in BBS calls  `StartActualLRP` and `EvacuateRunningActualLRP`.
This will allow BBS to store and pass through availability zone to the Route Emitter which will advertise in Registry Message for the Gorouter so that it can make decisions based on balancing algorithm.
[Feature] Diego advertises the availability zone of an LRP to enable clever intra-AZ routing
[tracker story](https://www.pivotaltracker.com/story/show/186117279)
[issue](https://github.com/cloudfoundry/routing-release/issues/356)
Thank you!
> Send AZ in StartActualLRP/EvacuateRunningActualLRP requests to BBS

- conversion_helpers.go
- conversion_helpers_test.go
Adds metric tags to tasks. Merge [this PR](https://github.com/cloudfoundry/bbs/pull/77) first.
Operator wants to see app/space/org names in task logs.
No consistency between LRP and task logs in regards to tags.
Task logs include tags.
https://github.com/cloudfoundry/bbs/pull/77
@acrmp 
Thank you!
> Adds metric tags to task logs

- evacuation/cleanup.go
- evacuation/cleanup_test.go
Summary
Evacuating actual LRP will be removed by BBS convergence or after the replacement LRP is started. No need to bombard BBS during cell updates. This will minimize the drain time and it will actually stay close to the configured drain timeout. Cleanup is happening after the timeout is reached and BBS requests can overload BBS and cause it to timeout each request (10s) by default.
> Do not remove evacuating actual LRP during cleanup

- cmd/rep/main.go
Summary
Merge in this PR once the PR to remove cfhttp v1 from dockerdriver is merged in:
- https://github.com/cloudfoundry/dockerdriver/pull/61
[#187603786](https://www.pivotaltracker.com/story/show/187603786)
Breaking Change? Nope
> Remove cfhttp v1 call, dockerdriver removed it

- cmd/rep/main_suite_test.go
Summary
We claim 6 ports per process but only increase by ginkgo node number which can be 1, 2, 3, etc
> Give 10 port buffer per process to avoid port collision

- evacuation/cleanup_test.go
Summary
This is a companion PR to https://github.com/cloudfoundry/diego-release/pull/947 fixing failing tests from removing the `replace` directive for `gomega`. The failing tests show errors with the following logs:
```
Cannot assign a value from the channel:\n    <chan error | len:1, cap:1>: 0xc00044f560\nTo:\n    <nil>: nil\nYou need to pass a pointer!
```
> Fix failing tests with replace directive removed for gomega

- cmd/rep/main.go
Summary
Use `Server` struct, which allows specifying a timeout, to address gosec G114
> Use Server struct to address gosec G114

- cmd/rep/main.go
Summary
Adds a ReadHeaderTimeout for http.Servers
Breaking Change? no
> Add read header timeout to address G112

- conversion_helpers.go
- conversion_helpers_test.go
Co-authored-by:
[Dimitar Dimitrov] <dimitar.dimitrov13@sap.com>
[Plamen Doychev] <plamen.doychev@sap.com>
Summary
Related to https://github.com/cloudfoundry/community/blob/main/toc/rfc/rfc-0030-add-support-for-file-based-service-binding.md
Breaking Change? **Yes/No**
> RFC-0030: Add support for file-based service bindings

- cmd/rep/config/config.go
- cmd/rep/main.go
- cmd/rep/main_test.go
Summary
The PR makes sure the FSes are used in a consistent way. We have added a SidecarRootFS that will store the FS to be used for the envoy & healthchecks.
The github issue: https://github.com/cloudfoundry/diego-release/issues/983
No breaking changes, just making sure the fses are used in a consistent way
<!---
> Add the SidecarFS functionality

- cmd/rep/config/config.go
- cmd/rep/main.go
- cmd/rep/main_test.go
Summary
This will help inject/load a rootfs from filesystem outside of rep.json configuration
> Add support for extra-rootfs-dir

- cmd/rep/main_test.go
Summary
Preloaded fs tests break the pipelines
Breaking Change? No
> Skip preloaded fs tests on Windows
